### ISSUE TITLE
Cutoff wavelength not working

### ISSUE THREAD

**Issue by acajic** [NCAR/bspline#1]
```

float* x = new float[8] {   0.f, 5.f, 10.f, 15.f, 20.f, 25.f, 30.f, 35.f};
float* y = new float[8]{    2.f, 4.f, 6.f,  8.f,  0.f,  6.f,  9.f,  4.f};
BSpline<float> bSpline(x, 8, y, 30.0);
bool ok = bSpline.ok();
float rez = bSpline.evaluate(2.f);

```

`ok` is `false` whenever I put anything other then 0 for `wl` and whenever `ok` is `false`, `rez` is 0.

**Comment by garyjg** [comment]
The algorithm which tries to find a reasonable number of nodes for a given wavelength was starting out at 9 intervals, which was already larger than your dataset, so it failed.  I have reduced it to 5, which works for your example, but I don't think there's any point in going lower.  Too low and assertions will fail because the basis function needs to be evaluated across multiple nodes.  I have also added some debug messages to the algorithm, to make it easier to get an explanation of what the algorithm is doing and why it is failing.  There is already a test program in the source, Tests/C++/bspline, which you can use to test examples like this one.  Just create a data file like the one attached, then run it like so:

bspline -i user8.txt -d -w 30

You will be able to see the debug messages, and you can also play with all the spline parameters to see how they affect the results, including the variance computed for all the Y values.

[user8.txt](https://github.com/ncareol/bspline/files/391167/user8.txt)
